Secret = [10, 57, 10, 3, 113, 48, 49, 18, 50, 234, 50, 60, 0, 162, 41, 93, 110, 157, 7, 177, 163, 146, 76, 193, 250, 252, 38, 226, 248, 199, 122, 141, 21, 207, 17, 68, 156, 103, 39, 158, 142, 22, 236, 205, 139, 23, 203, 38, 146, 57, 73, 54, 82, 229, 83, 76, 190, 26, 248, 10, 57, 10, 3, 113, 98, 49, 18, 50, 205, 27, 30, 229, 220, 237, 213, 180, 133, 125, 222, 14, 221, 56, 50, 127, 251, 39, 106, 9, 87, 182, 20, 70, 248, 74, 195, 237, 22, 190, 45, 58, 24, 140, 130, 125, 224, 247, 58, 156, 216, 245, 114, 115, 180, 206, 237, 200, 88, 87, 10, 45, 10, 9, 115, 101, 99, 114, 101, 116, 107, 101, 121, 18, 32, 127, 17, 172, 66, 160, 43, 115, 14, 177, 122, 83, 129, 200, 254, 93, 113, 36, 138, 53, 8, 14, 47, 188, 43, 101, 126, 64, 107, 166, 228, 41, 190, 10, 57, 10, 3, 112, 48, 49, 18, 50, 157, 164, 5, 140, 16, 158, 233, 47, 75, 53, 125, 129, 222, 141, 139, 9, 217, 192, 128, 69, 103, 113, 100, 238, 127, 251, 97, 10, 129, 203, 135, 236, 106, 164, 250, 121, 220, 75, 165, 44, 83, 80, 243, 159, 33, 244, 82, 10, 19, 241]

[[Systems]]
  name = "q01"
  usage = "test"
  Tags = []
  User = "sapaut"
  lang = "en"
  client = "100"
  Server = "euleq01"
  Sysnr = "01"

[[Systems]]
  Name = "p01"
  usage = "test"
  Tags = []
  User = "sapaut"
  Lang = "en"
  CLIENT = "100"
  Server = "eulepa"
  sysnr = "01"

[[Systems]]
  Name = "qb1"
  Usage = "test"
  tags = []
  User = "sapaut"
  Lang = "en"
  Client = "100"
  server = "bwq01"
  Sysnr = "21"

[[TableMetrics]]
  name = "sap_users"
  Help = "sm04 help"
  metricType = "gauge"
  TagFilter = []
  AllServers = true
  functionModule = "TH_USER_LIST"
  Table = "USRLIST"
  [TableMetrics.RowCount]
    Guiversion = ["76", "75", "74"]
    mandt = ["000", "090", "100", "400"]
    TYPE = [4]
  [TableMetrics.RowFilter]

[[TableMetrics]]
  name = "sap_lock_entries"
  Help = "sm12 help"
  MetricType = "gauge"
  tagFilter = []
  AllServers = false
  functionmodule = "ENQUE_READ"
  Table = "ENQ"
  [TableMetrics.Params]
    GARG = ""
    GCLIENT = ""
    GNAME = ""
    GUNAME = ""
  [TableMetrics.RowCount]
    gclient = ["000", "090", "100", "400"]
  [TableMetrics.RowFilter]
#
[[TableMetrics]]
  Name = "sap_processes"
  Help = "sm50 help"
  MetricType = "gauge"
  TagFilter = []
  AllServers = true
  FunctionModule = "TH_WPINFO"
  Table = "WPLIST"
  [TableMetrics.Params]
    SRVNAME = ""
  [TableMetrics.RowCount]
    wp_table = ["dbvm", "dbvl", "ma61v", "mdup"]
    wp_typ = ["dia", "btc", "upd", "upd2"]
  [TableMetrics.RowFilter]
    wp_status = ["on hold", "running"]
#
[[FieldMetrics]]
  Name = "sap_kernel_info"
  Help = "SAP kernel and db client info"
  MetricType = "gauge"
  TagFilter = []
  AllServers = true
  FunctionModule = "TH_SAPREL2"
  fieldLabels = ["kern_rel", "kern_dblib", "kern_patchlevel"]
